#!/bin/sh -e
declare -A opt
while getopts 'fnpi' o ; do
	opt[$o]=$OPTARG
done
shift $[OPTIND-1]
setup=dist/setup/setup
solr_setup=solr/scripts/setup_solr.sh
mkdir -p `dirname $setup`
ghc -Wall -fwarn-tabs --make -odir dist/setup -hidir dist/setup -i. Setup.hs -o $setup
[[ -z ${opt[f]+set} && -f dist/setup-config ]] || $setup configure --user -f ${opt[p]+-}devel
$setup build -j3
if [[ -n ${opt[i]+set} ]] ; then
	$setup install "$@"
elif [[ -z ${opt[n]+set}${opt[p]+set} ]] ; then
        echo "Starting solr..."
        $solr_setup
	echo "Starting databrary..."
	databrary_datadir=. databrary_sysconfdir=. dist/build/databrary/databrary "$@"
fi
